# Generated by Django 3.1.1 on 2022-01-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
